[settings]
experimental = true
activate_aggressive = true
color_theme = "catppuccin"
install_before = "7d"
pin = true
trusted_config_paths = [
    '~/Projects',
    '/workspaces'
]

[settings.npm]
package_manager = "bun"

[settings.python]
uv_venv_auto = "create|source"

[env]
MISE_AGE_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOW8rM3RwSjhsWVFXZldQY2pVWnRTdGVmM1NHQ0xvaTFtNHVMMUF1WWdVClphN0Jvck1XZjdiY3N6KzgzKzA1cnAyVzBjM2NZL3NCaDU3NEphek1MMFEKLT4gc3NoLWVkMjU1MTkgaytYQ0RnIEo1cFBEVVlob1dOQkN2VUthMEJyRmtZalBhVjZHT0VLdldIemR6QTNNVDAKQkVQd1FvWkxzSXdMaEtHYmg3cm1yaU81aE1xTFc4ZmpoaVRXNlBmL3ZDOAotPiAhLWdyZWFzZSBoYVEgZ1hsWnZbamEgVnxFNAprMkFaT3h4M2o5L3ZEMFdLZHY0TXU5NDhOaUVlYjE2MzJUcwotLS0gRXRCcXhDTnlRVnM2MDlQS1dIQktYR2Z5Tko5TGlJNm9DWml5T1A0bEJRTQpaME5m5x+myDencHsVxMDKEbhxvMT3StQghqsEIHkyvisf/09+7VgTo3gaAzle8LtKzhg0p69xAu8PbtkbPtaEdYhsa/Cs7Ap0UfTpIGiF7eehgfUvT9HZmu3VBKfegJOi4shvi5tnT2eX" }
GITHUB_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2ZZMzlqRUprWW5GTnBOMlY0VUpFdEc1RXIrZTFPQ3dqcmcvQktRTVRnCnNQQUs1U0lqUUl0WG5JNVBHL3AyNFRoRDI1TDByMzZzQXYvU2lmZENSUWcKLT4gc3NoLWVkMjU1MTkgaytYQ0RnIGsrcmhwRXBuSDNJMkpPamVwYlFqWXdpV1JlZ2ZzWmNzV1lTK0dsT0lhRW8KYy9sRDhnOGJxR1hsMW9uaDEreCs3aStXZjV6UXk1YkJ3cmU0d2ZJTG5vVQotPiAjdyt1Q3pKUS1ncmVhc2UgKlwkOHdxIEd4XTddUyAzOGgKSjJSWFprVFAKLS0tIDcxOXVGSng5blppOUVZL1Zrclk4R0dyQzBVWUhQclR3OXUvRXdJMU0rNmcKXZTVid/Ic9bB0+OvuF9fqcIDfGj/5YBbexFrL+cWPyBeuYthyjFGjd3B8Gj7h0doDt8QDYq7JtnrbnJmIe7EJJfFQhtvdJKW" }
SHELL = "fish"
EDITOR = "hx"
PAGER = "bat"
BAT_THEME = "Catppuccin Mocha"

[tools]
age = "1.3.1"
bat = "0.26.1"
bun = "1.3.9"
cargo-binstall = "1.17.5"
chezmoi = "2.69.4"
fd = "10.3.0"
fnox = "1.12.1"
fzf = "0.67.0"
gh = "2.87.0"
helix = "25.07.1"
lazydocker = "0.24.4"
lazygit = "0.59.0"
node = "22.22.0"
pitchfork = "1.4.3"
ripgrep = "15.1.0"
starship = "1.24.2"
uv = "0.10.4"
yazi = "26.1.22"
zoxide = "0.9.9"

[shell_alias]
cm = "chezmoi"
y = "yazi"
lg = "lazygit"
ld = "lazydocker"
dc = "docker compose"
ts = "tailscale"
taltech = "sudo openfortivpn vpn.taltech.ee:443 --saml-login"

